# This workflow should generate a new git tag and corresponding GitHub release
# every time the VERSION file is updated.
#
# The version number in the file is used as the release tag.
name: auto-release

"on":
  push:
    branches:
      - main
    paths:
      - "VERSION"

jobs:
  auto-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: get version
        id: get_version
        run: echo "version=v$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.get_version.outputs.version }}"

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
